import fs from "node:fs";
import path from "node:path";
import { prisma } from "@/server/db";
import { AppError } from "@/lib/errors";
import { isBuildPhase } from "@/lib/utils";
import { assertSafeFileName } from "@/server/storage/path-resolver";
import { isBlockedSystemPath } from "@/server/storage/host-fs";
import { normalizeBrowsePath } from "@/server/storage/browse-linux";

export const EXTRA_VOLUMES_KEY = "storage.extraVolumes";
export const EXTRA_VOLUMES_DIR = "volumes";
export const COMPOSE_VOLUMES_FILE = "docker-compose.cloudora-volumes.yml";
export const SIGNAL_VOLUMES_FILE = "extra-volumes.yml";
export const SIGNAL_COMPOSE_UP = "compose-up";

export type ExtraVolume = {
  id: string;
  name: string;
  hostPath: string;
};

const ID_RE = /^[a-z][a-z0-9_-]{0,31}$/;
const RESERVED = new Set(["users", "shared", "volumes", "trash", "host"]);

export function slugifyVolumeId(input: string): string {
  const slug = input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 32);
  return slug;
}

export function parseExtraVolumes(value: unknown): ExtraVolume[] {
  if (!Array.isArray(value)) return [];
  const seen = new Set<string>();
  const out: ExtraVolume[] = [];
  for (const item of value) {
    if (!item || typeof item !== "object") continue;
    const rec = item as Record<string, unknown>;
    const id = slugifyVolumeId(String(rec.id ?? rec.name ?? ""));
    const hostPath = String(rec.hostPath ?? "").trim();
    const name = String(rec.name ?? id).trim() || id;
    if (!id || seen.has(id)) continue;
    try {
      const vol = normalizeExtraVolume({ id, name, hostPath });
      seen.add(vol.id);
      out.push(vol);
    } catch {
      /* skip invalid */
    }
  }
  return out;
}

export function normalizeExtraVolume(input: { id: string; name: string; hostPath: string }): ExtraVolume {
  const id = slugifyVolumeId(input.id || input.name);
  if (!ID_RE.test(id) || RESERVED.has(id)) {
    throw new AppError("INVALID_PATH", "Ungültiger Volume-Name. Nur a-z, 0-9, Bindestrich. Nicht users/shared/volumes.", 400);
  }
  assertSafeFileName(id);
  const hostPath = normalizeBrowsePath(input.hostPath);
  if (hostPath === "/") {
    throw new AppError("INVALID_PATH", "Die Wurzel / kann nicht als Volume gelinkt werden. Wähle z. B. /mnt/hdd oder /home.", 400);
  }
  if (isBlockedSystemPath(hostPath, null)) {
    throw new AppError("FORBIDDEN", "Dieser Systempfad kann nicht gelinkt werden.", 403);
  }
  const name = input.name.trim() || id;
  if (name.length > 64) {
    throw new AppError("INVALID_PATH", "Der Anzeigename ist zu lang.", 400);
  }
  return { id, name, hostPath };
}

export function extraVolumeContainerPath(storagePath: string, id: string): string {
  const root = storagePath.replace(/\/+$/, "") || "/storage";
  return `${root}/${EXTRA_VOLUMES_DIR}/${id}`;
}

function yamlScalar(value: string): string {
  if (value === "" || /[\s:#{}[\],&*?|<>=!%@`'"]/.test(value)) return JSON.stringify(value);
  return value;
}

export function extraVolumesComposeYaml(volumes: ExtraVolume[], storagePath: string): string {
  if (volumes.length === 0) {
    return "# Generated by Cloudora. Do not edit.\n# No extra volumes.\nservices: {}\n";
  }
  const lines = ["# Generated by Cloudora. Do not edit.", "services:", "  cloudora:", "    volumes:"];
  for (const vol of volumes) {
    const target = extraVolumeContainerPath(storagePath, vol.id);
    lines.push(`      - ${yamlScalar(vol.hostPath)}:${yamlScalar(target)}`);
  }
  return `${lines.join("\n")}\n`;
}

let cachedVolumes: ExtraVolume[] | null = null;
let volumesLoaded = false;

export async function hydrateExtraVolumes(): Promise<ExtraVolume[]> {
  if (volumesLoaded && cachedVolumes) return cachedVolumes;
  if (isBuildPhase()) {
    cachedVolumes = [];
    return cachedVolumes;
  }
  try {
    const row = await prisma.setting.findUnique({ where: { key: EXTRA_VOLUMES_KEY } });
    cachedVolumes = parseExtraVolumes(row?.value);
    volumesLoaded = true;
  } catch {
    cachedVolumes = [];
  }
  return cachedVolumes;
}

export async function saveExtraVolumes(input: ExtraVolume[]): Promise<ExtraVolume[]> {
  const seen = new Set<string>();
  const next: ExtraVolume[] = [];
  for (const item of input) {
    const vol = normalizeExtraVolume(item);
    if (seen.has(vol.id) || seen.has(vol.hostPath)) {
      throw new AppError("CONFLICT", "Volume-Name oder Host-Pfad ist doppelt.", 409);
    }
    seen.add(vol.id);
    seen.add(vol.hostPath);
    next.push(vol);
  }
  await prisma.setting.upsert({
    where: { key: EXTRA_VOLUMES_KEY },
    update: { value: next },
    create: { key: EXTRA_VOLUMES_KEY, value: next },
  });
  cachedVolumes = next;
  volumesLoaded = true;
  return next;
}

export function ensureExtraVolumeDirs(storagePath: string, volumes: ExtraVolume[]): void {
  const root = path.join(storagePath.replace(/\/+$/, "") || "/storage", EXTRA_VOLUMES_DIR);
  fs.mkdirSync(root, { recursive: true });
  for (const vol of volumes) {
    fs.mkdirSync(path.join(root, vol.id), { recursive: true });
  }
}

export function writeVolumeApplySignal(signalDir: string, yaml: string): void {
  fs.mkdirSync(signalDir, { recursive: true });
  fs.writeFileSync(path.join(signalDir, SIGNAL_VOLUMES_FILE), yaml, "utf8");
  const dest = path.join(signalDir, SIGNAL_COMPOSE_UP);
  const tmp = `${dest}.tmp`;
  fs.writeFileSync(tmp, `${new Date().toISOString()}\n`, "utf8");
  fs.renameSync(tmp, dest);
}
